In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
X, y = load_iris(return_X_y=True)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [6]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [7]:
X_train_scaled #use print in vs code

array([[-0.88724609,  0.90994593, -1.45636583, -1.4067585 ],
       [ 0.45275945, -0.54921013,  0.66859779,  0.30371949],
       [ 1.42730893, -0.06282477,  1.12804938,  1.09317087],
       [-0.27815266, -1.03559548, -0.2503054 , -0.35415666],
       [-0.27815266,  1.88271663, -1.28407149, -1.27518327],
       [ 1.30549024,  0.42356058,  0.43887199,  0.17214426],
       [ 0.20912208, -0.54921013,  0.43887199, -0.0910062 ],
       [-0.52179004, -1.27878815,  0.03685185,  0.04056903],
       [ 0.33094076, -0.30601745,  0.20914619,  0.04056903],
       [ 0.45275945, -1.76517351,  0.26657764,  0.04056903],
       [-1.00906478,  0.90994593, -1.39893438, -1.4067585 ],
       [-0.27815266, -1.27878815,  0.61116634,  0.96159564],
       [ 0.33094076,  0.90994593,  0.84089214,  1.35632133],
       [ 1.06185287,  0.42356058,  1.12804938,  1.35632133],
       [ 0.08730339, -0.7924028 ,  0.66859779,  0.43529472],
       [ 0.57457813, -0.30601745,  0.20914619,  0.04056903],
       [-1.13088346,  1.

In [9]:
import numpy as np
(X_train - np.mean(X_train, axis = 0)) / np.std(X_train,axis = 0) #this is what standardscaler is doing which we just did manually

array([[-0.88724609,  0.90994593, -1.45636583, -1.4067585 ],
       [ 0.45275945, -0.54921013,  0.66859779,  0.30371949],
       [ 1.42730893, -0.06282477,  1.12804938,  1.09317087],
       [-0.27815266, -1.03559548, -0.2503054 , -0.35415666],
       [-0.27815266,  1.88271663, -1.28407149, -1.27518327],
       [ 1.30549024,  0.42356058,  0.43887199,  0.17214426],
       [ 0.20912208, -0.54921013,  0.43887199, -0.0910062 ],
       [-0.52179004, -1.27878815,  0.03685185,  0.04056903],
       [ 0.33094076, -0.30601745,  0.20914619,  0.04056903],
       [ 0.45275945, -1.76517351,  0.26657764,  0.04056903],
       [-1.00906478,  0.90994593, -1.39893438, -1.4067585 ],
       [-0.27815266, -1.27878815,  0.61116634,  0.96159564],
       [ 0.33094076,  0.90994593,  0.84089214,  1.35632133],
       [ 1.06185287,  0.42356058,  1.12804938,  1.35632133],
       [ 0.08730339, -0.7924028 ,  0.66859779,  0.43529472],
       [ 0.57457813, -0.30601745,  0.20914619,  0.04056903],
       [-1.13088346,  1.

In [10]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
X_train # this is what minmaxscaler is doing and use print fn in vs code for this line 

array([[0.26470588, 0.58333333, 0.06779661, 0.04166667],
       [0.58823529, 0.33333333, 0.69491525, 0.58333333],
       [0.82352941, 0.41666667, 0.83050847, 0.83333333],
       [0.41176471, 0.25      , 0.42372881, 0.375     ],
       [0.41176471, 0.75      , 0.11864407, 0.08333333],
       [0.79411765, 0.5       , 0.62711864, 0.54166667],
       [0.52941176, 0.33333333, 0.62711864, 0.45833333],
       [0.35294118, 0.20833333, 0.50847458, 0.5       ],
       [0.55882353, 0.375     , 0.55932203, 0.5       ],
       [0.58823529, 0.125     , 0.57627119, 0.5       ],
       [0.23529412, 0.58333333, 0.08474576, 0.04166667],
       [0.41176471, 0.20833333, 0.6779661 , 0.79166667],
       [0.55882353, 0.58333333, 0.74576271, 0.91666667],
       [0.73529412, 0.5       , 0.83050847, 0.91666667],
       [0.5       , 0.29166667, 0.69491525, 0.625     ],
       [0.61764706, 0.375     , 0.55932203, 0.5       ],
       [0.20588235, 0.66666667, 0.06779661, 0.04166667],
       [0.70588235, 0.20833333,

In [13]:
X_min = np.min(X_train, axis=0)
X_max = np.max(X_train, axis = 0)
(X_train - X_min) / (X_max - X_min)  #and here we did it manually what the minmaxscaler is doing exactly

array([[0.26470588, 0.58333333, 0.06779661, 0.04166667],
       [0.58823529, 0.33333333, 0.69491525, 0.58333333],
       [0.82352941, 0.41666667, 0.83050847, 0.83333333],
       [0.41176471, 0.25      , 0.42372881, 0.375     ],
       [0.41176471, 0.75      , 0.11864407, 0.08333333],
       [0.79411765, 0.5       , 0.62711864, 0.54166667],
       [0.52941176, 0.33333333, 0.62711864, 0.45833333],
       [0.35294118, 0.20833333, 0.50847458, 0.5       ],
       [0.55882353, 0.375     , 0.55932203, 0.5       ],
       [0.58823529, 0.125     , 0.57627119, 0.5       ],
       [0.23529412, 0.58333333, 0.08474576, 0.04166667],
       [0.41176471, 0.20833333, 0.6779661 , 0.79166667],
       [0.55882353, 0.58333333, 0.74576271, 0.91666667],
       [0.73529412, 0.5       , 0.83050847, 0.91666667],
       [0.5       , 0.29166667, 0.69491525, 0.625     ],
       [0.61764706, 0.375     , 0.55932203, 0.5       ],
       [0.20588235, 0.66666667, 0.06779661, 0.04166667],
       [0.70588235, 0.20833333,